/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package currencycalc;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;
import java.util.ArrayList;
import java.util.stream.Collectors;
import javax.net.ssl.HttpsURLConnection;
import javax.swing.DefaultComboBoxModel;
import jdk.nashorn.internal.parser.JSONParser;
import org.json.JSONObject;

/**
 *
 * @author ross
 */
public class CurrencyConverter extends javax.swing.JPanel {
    ArrayList<Currency> currencies;
    String[] currencyStrings;

    /**
     * Creates new form CurrencyConverter
     */
    public CurrencyConverter() {
        currencies = new ArrayList<>(); 
        currencies.add(Currency.GBP);
        currencies.add(Currency.EUR);
        currencies.add(Currency.AUD);
        currencies.add(Currency.BTC);
        currencies.add(Currency.CAD);
        currencies.add(Currency.INR);
        currencies.add(Currency.SGD);
        currencies.add(Currency.USD);
        
        currencyStrings = new String[currencies.size()];
        
        for (int i = 0; i < currencies.size(); i++){
            currencyStrings[i] = currencies.get(i).toString();
        }
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        firstCurrency = new javax.swing.JComboBox<>();
        secondCurrency = new javax.swing.JComboBox<>();
        firstCurrencyAmount = new javax.swing.JTextField();
        seccondCurrencyAmmount = new javax.swing.JLabel();
        claculateButton = new javax.swing.JButton();
        firstCurrencySymbol = new javax.swing.JLabel();
        secondCurrencySymbol = new javax.swing.JLabel();
        connectionStatus = new javax.swing.JLabel();

        backButton.setText("Back to menu");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Currency Converter");

        firstCurrency.setModel(new DefaultComboBoxModel<String>(currencyStrings));
        firstCurrency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstCurrencyActionPerformed(evt);
            }
        });

        secondCurrency.setModel(new DefaultComboBoxModel<String>(currencyStrings));
        secondCurrency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondCurrencyActionPerformed(evt);
            }
        });

        firstCurrencyAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstCurrencyAmountActionPerformed(evt);
            }
        });

        seccondCurrencyAmmount.setText("0");

        claculateButton.setText("Calculate");
        claculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claculateButtonActionPerformed(evt);
            }
        });

        firstCurrencySymbol.setText("£");

        secondCurrencySymbol.setText("£");

        connectionStatus.setForeground(new java.awt.Color(0, 204, 51));
        connectionStatus.setText("Internet connection required");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(firstCurrencySymbol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(firstCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(secondCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(firstCurrencyAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(secondCurrencySymbol)
                                .addGap(48, 48, 48))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(connectionStatus)
                                .addGap(22, 22, 22))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(claculateButton)
                                .addGap(59, 59, 59)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seccondCurrencyAmmount, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstCurrencyAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstCurrencySymbol)
                    .addComponent(secondCurrencySymbol)
                    .addComponent(seccondCurrencyAmmount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(claculateButton)
                .addGap(30, 30, 30)
                .addComponent(connectionStatus)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void firstCurrencyAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstCurrencyAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstCurrencyAmountActionPerformed

    private void claculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claculateButtonActionPerformed
        System.out.print("Connecting to Yahoo Finance");
        connectionStatus.setText("Connecting to Yahoo Finance");
        System.out.println(".");
        Currency firstCurrencyValue = currencies.get(firstCurrency.getSelectedIndex());
        Currency seccondCurrencyValue = currencies.get(secondCurrency.getSelectedIndex());
        
        double rate;
        
        try {
            rate = firstCurrencyValue.getRate(seccondCurrencyValue);
        } catch (RuntimeException e) {
            connectionStatus.setText(e.getMessage());
            return;
        }
        
        double seccondCurrencyAmmountDouble =
                Math.round(Double.parseDouble(firstCurrencyAmount.getText()) * rate);
        
        seccondCurrencyAmmount.setText(String.valueOf(seccondCurrencyAmmountDouble));
        connectionStatus.setText("Internet connection required");
    }//GEN-LAST:event_claculateButtonActionPerformed

    private void firstCurrencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstCurrencyActionPerformed
        firstCurrencySymbol.setText(currencies.get(firstCurrency.getSelectedIndex()).getSymbol());
    }//GEN-LAST:event_firstCurrencyActionPerformed

    private void secondCurrencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondCurrencyActionPerformed
        secondCurrencySymbol.setText(currencies.get(secondCurrency.getSelectedIndex()).getSymbol());
    }//GEN-LAST:event_secondCurrencyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton backButton;
    private javax.swing.JButton claculateButton;
    private javax.swing.JLabel connectionStatus;
    private javax.swing.JComboBox<String> firstCurrency;
    private javax.swing.JTextField firstCurrencyAmount;
    private javax.swing.JLabel firstCurrencySymbol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel seccondCurrencyAmmount;
    private javax.swing.JComboBox<String> secondCurrency;
    private javax.swing.JLabel secondCurrencySymbol;
    // End of variables declaration//GEN-END:variables
}
